export enum Categorie {
    Animaux = 0,
    AnimauxTerrestres = 1,
    AnimauxVolants = 2,
    AnimauxAquatiques = 3,
    AlcoolBoissons = 5,
    MedecineSante = 6,
    MusiqueArts = 7,
    EtudesDisciplines = 8,
    VieSentimentaleSexuelle = 9,
    NourritureGastronomie = 10,
    GeographieRegions = 11,
    HonneursDistinctions = 12,
    BlamesSanctions = 13,
    TransportVehicules = 14,
    LoisirsPassions = 15,
    VieAssociativeAdministrative = 16,
    AptitudesTraitsCaractere = 17,
    FamilleParrainage = 18,
    LettresChiffres = 19,
    OutilsObjets = 20,
    VegetauxNature = 21,
    HistoireAntiquite = 22,
}

export function toStringCategorie(categorie: Categorie): string {
    const map: Record<Categorie, string> = {
        [Categorie.Animaux]: "Animaux",
        [Categorie.AnimauxTerrestres]: "Animaux terrestres",
        [Categorie.AnimauxVolants]: "Animaux volants",
        [Categorie.AnimauxAquatiques]: "Animaux aquatiques",
        [Categorie.AlcoolBoissons]: "Alcool / Boissons",
        [Categorie.MedecineSante]: "Médecine / Santé",
        [Categorie.MusiqueArts]: "Musique / Arts",
        [Categorie.EtudesDisciplines]: "Études / Disciplines",
        [Categorie.VieSentimentaleSexuelle]: "Vie sentimentale / sexuelle",
        [Categorie.NourritureGastronomie]: "Nourriture / Gastronomie",
        [Categorie.GeographieRegions]: "Géographie / Régions",
        [Categorie.HonneursDistinctions]: "Honneurs / Distinctions",
        [Categorie.BlamesSanctions]: "Blâmes / Sanctions",
        [Categorie.TransportVehicules]: "Transport / Véhicules",
        [Categorie.LoisirsPassions]: "Loisirs / Passions",
        [Categorie.VieAssociativeAdministrative]: "Vie associative / administrative",
        [Categorie.AptitudesTraitsCaractere]: "Aptitudes / Traits de caractère",
        [Categorie.FamilleParrainage]: "Famille / Parrainage",
        [Categorie.LettresChiffres]: "Lettres / Chiffres",
        [Categorie.OutilsObjets]: "Outils / Objets",
        [Categorie.VegetauxNature]: "Végétaux / Nature",
        [Categorie.HistoireAntiquite]: "Histoire / Antiquité",
    };
    return map[categorie] ?? "Inconnu";
}