export enum Categorie {
    Animaux = 0,
    AnimauxTerrestres = 1,
    AnimauxVolants = 2,
    AnimauxAquatiques = 3,
    AnimauxMythologiques = 4,
    AlcoolBoissons = 5,
    MedecineSante = 6,
    MusiqueArts = 7,
    EtudesDisciplines = 8,
    VieSentimentaleSexuelle = 9,
    NourritureGastronomie = 10,
    GeographieRegions = 11,
    HonneursDistinctions = 12,
    BlamesSanctions = 13,
    TransportVehicules = 14,
    LoisirsPassions = 15,
    VieAssociativeAdministrative = 16,
    AptitudesTraitsCaractere = 17,
    FamilleParrainage = 18,
    LettresChiffres = 19,
    OutilsObjets = 20,
    VegetauxNature = 21,
    HistoireAntiquite = 22,
    Divers = 23,
}
